###########################################################################
## Graphics
###########################################################################

pyplot.figure(figsize=(8, 6), dpi=300, facecolor='w', edgecolor='k')
pyplot.plot(thickness*1.0e7, data_1[4], linewidth=0.8)
pyplot.plot(thickness*1.0e7, data_1[4], 'o')
#pyplot.plot(thickness*1.0e7, data_2[4], linewidth=0.8)
#pyplot.plot(thickness*1.0e7, data_2[4], 'o')
pyplot.xlabel('Thickness [nm]', {'fontsize':8})
pyplot.ylabel('$J_{sc}$ [mA/cm$^{2}$]', {'fontsize':8})
pyplot.title('Short-circuit current density', {'fontsize':10})
pyplot.grid(True)
#pyplot.axis([490, 3010, 34.4, 34.9])
pyplot.savefig('jSC81.pdf')
pyplot.show()

pyplot.figure(figsize=(8, 6), dpi=300, facecolor='w', edgecolor='k')
pyplot.plot(thickness*1.0e7, data_1[3] , linewidth=0.8)
pyplot.plot(thickness*1.0e7, data_1[3], 'o')
#pyplot.plot(thickness*1.0e7, data_2[3] , linewidth=0.8)
#pyplot.plot(thickness*1.0e7, data_2[3], 'o')
pyplot.xlabel('Thickness [nm]', {'fontsize':8})
pyplot.ylabel('FF [%]', {'fontsize':8})
pyplot.title('Fill factor', {'fontsize':10})
pyplot.grid(True)
#pyplot.axis([490, 3010, 34.4, 34.9])
pyplot.savefig('FF81.pdf')
pyplot.show()

pyplot.figure(figsize=(8, 6), dpi=300, facecolor='w', edgecolor='k')
pyplot.plot(thickness*1.0e7, data_1[2]*1e3 , linewidth=0.8)
pyplot.plot(thickness*1.0e7, data_1[2]*1e3, 'o')
#pyplot.plot(thickness*1.0e7, data_2[2]*1e3 , linewidth=0.8)
#pyplot.plot(thickness*1.0e7, data_2[2]*1e3, 'o')
pyplot.xlabel('Thickness [nm]', {'fontsize':8})
pyplot.ylabel('$V_{oc}$ [mV]', {'fontsize':8})
pyplot.title('Open-circuit voltage', {'fontsize':10})
pyplot.grid(True)
#pyplot.axis([490, 3010, 34.4, 34.9])
pyplot.savefig('Voc81.pdf')
pyplot.show()

pyplot.figure(figsize=(8, 6), dpi=300, facecolor='w', edgecolor='k')
pyplot.plot(thickness*1.0e7, data_1[1] , linewidth=0.8)
pyplot.plot(thickness*1.0e7, data_1[1], 'o')
#pyplot.plot(thickness*1.0e7, data_2[1] , linewidth=0.8)
#pyplot.plot(thickness*1.0e7, data_2[1], 'o')
pyplot.xlabel('Thickness [nm]', {'fontsize':8})
pyplot.ylabel('$\\eta$ [%]', {'fontsize':8})
pyplot.title('Efficiency', {'fontsize':10})
pyplot.grid(True)
pyplot.savefig('Effi81.pdf')
pyplot.show()

pyplot.figure(figsize=(8, 6), dpi=300, facecolor='w', edgecolor='k')
pyplot.plot(wlengthsQE, EQE, label='EQE', linewidth=0.8)
pyplot.plot(wlengthsQE, IQE, label='IQE', linewidth=0.8)
pyplot.xlabel('Wave length [nm]', {'fontsize':8})
pyplot.ylabel('QE', {'fontsize':8})
pyplot.title('Quantum Efficciency', {'fontsize':10})
pyplot.legend(loc='best')
pyplot.grid(True)
pyplot.savefig('QE8-300dpi.pdf')
pyplot.show()

fig, ax1, = pyplot.subplots(figsize=(8, 6), dpi=300, facecolor='w', edgecolor='k')
ax1.set_xlabel('Wave length [nm]', {'fontsize':8})
ax1.set_ylabel('Transmittance [%]', {'fontsize':8})
ax1.plot(wlengths, T, label='Transmittance TCO', linewidth=1.2)
ax1.tick_params(axis='y')
ax2 = ax1.twinx()  # instantiate a second axes that shares the same x-axis
ax2.set_ylabel('Reflectance [%]', {'fontsize':8})  # we already handled the x-label with ax1
ax2.plot(wlengths, R, label='Reflectance CIGS', linewidth=1.2, color='g')
ax2.tick_params(axis='y')
fig.tight_layout()# otherwise the right y-label is slightly clipped
ax1.grid(True)
fig.legend(loc='center', fontsize='small')
pyplot.savefig('RT8-300dpi.pdf')
pyplot.show()

pyplot.figure(figsize=(8, 6), dpi=300, facecolor='w', edgecolor='k')
pyplot.plot(Vone, Jone, linewidth=0.8)
pyplot.xlabel('Voltage [V]', {'fontsize':8})
pyplot.ylabel('Current density [mA/cm²]', {'fontsize':8})
pyplot.title('Current Voltage Curve', {'fontsize':10})
pyplot.grid() 
pyplot.savefig('JV8-300dpi.pdf')
pyplot.show()
